### ISSUE TITLE
Which are nuke cards?

### ISSUE THREAD

**Issue by natevw** [adambrault/kerblam#2]
Do I understand that basically whenever you want to play a numbered card as a nuke, you just say so?

**Comment by latentflip** [comment]
I am also trying to figure that bit out.

**Comment by latentflip** [comment]
Oohh, my guess it's jokers (2 nukes for two players) or for multiplayer you use some of the removed 2s/3s for nukes.

**Comment by adamavenir** [comment]
@latentflip is right. I missed adding this info to the docs. I'll do that.

There has historically been some disagreement among players as to whether larger games with more players should add more nukes, remove more cards, or some combination of both.

Nukes are quite dramatic, so on first read and introduction people like the idea of having more of them. In my experience, when you add more than 2-3 per person, it feels like the game is just nuke after nuke.
